name: Run OpenSIPS Conformance Tests

on:
  # Triggers the workflow on all push or pull request events
  push:
  pull_request:
  workflow_run:
    workflows:
      - Build SIPSsert Image
    types:
      - completed
  schedule:
    - cron: '0 2 * * Mon'
  workflow_call:

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:

    - name: Checkout Tests repo
      uses: actions/checkout@v4
      with:
        repository: OpenSIPS/sipssert-opensips-tests
        path: tests

    - name: Read and parse YAML file
      id: set-matrix
      uses: OpenSIPS/SIPssert/.github/actions/Set_Matrix@main


  test:
    needs: setup-matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.setup-matrix.outputs.matrix)}}
    runs-on: ${{ matrix.os }}

    steps:

    - name: Prepare SIPssert
      uses: OpenSIPS/SIPssert/.github/actions/Prepare_SIPssert@main
      with:
        sipssert-repo: OpenSIPS/SIPSsert
        tests-repo: OpenSIPS/sipssert-opensips-tests

    - name: Run Test
      uses: OpenSIPS/SIPssert/.github/actions/Run_Tests@main
      with:
        tests: ${{ matrix.tests }}

  aggregate:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Sparse Checkout
      run: |
        git sparse-checkout init --cone
        git sparse-checkout set .github/scripts/aggregate_junit_reports.py
        git checkout

    - name: Debug Script Location
      run: ls -R .github/scripts

    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: junit-reports

    - name: Aggregate JUnit Reports
      run: |
        pip install junitparser
        python .github/scripts/aggregate_junit_reports.py
      env:
        REPORTS_DIR: junit-reports
        OUTPUT_FILE: junit-final-report.xml

    - name: Upload JUnit XML
      uses: actions/upload-artifact@v4
      with:
        name: junit-final-report
        path: junit-final-report.xml

    - name: Display Final Summary Table
      uses: mikepenz/action-junit-report@v3
      with:
        check_name: 'Aggregated SIPssert Test Report'
        report_paths: junit-final-report.xml
        fail_on_failure: false
