name: Run OpenSIPS Conformance Tests

on:
  # Triggers the workflow on all push or pull request events
  push:
  pull_request:
  workflow_run:
    workflows:
      - Build SIPSsert Image
    types:
      - completed
  schedule:
    - cron: '0 2 * * Mon'
  workflow_call:

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:

    - name: Checkout Tests repo
      uses: actions/checkout@v4
      with:
        repository: OpenSIPS/sipssert-opensips-tests
        path: tests

    - name: Read and parse YAML file
      id: set-matrix
      uses: OpenSIPS/SIPssert/.github/actions/Set_Matrix@main

  test:
    needs: setup-matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.setup-matrix.outputs.matrix)}}
    runs-on: ${{ matrix.os }}

    steps:

    - name: Prepare SIPssert
      uses: OpenSIPS/SIPssert/.github/actions/Prepare_SIPssert@main
      with:
        sipssert-repo: OpenSIPS/SIPSsert
        tests-repo: OpenSIPS/sipssert-opensips-tests

    - name: Run Test
      uses: dariusstefan/SIPssert/.github/actions/Run_Tests@pull-req
      with:
        tests: ${{ matrix.tests }}

  aggregate:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: junit-reports

    - name: Aggregate JUnit Reports
      run: |
        pip install junitparser
        python .github/scripts/aggregate_junit_reports.py
      env:
        REPORTS_DIR: junit-reports
        OUTPUT_FILE: junit-final-report.xml

    - name: Upload JUnit XML
      uses: actions/upload-artifact@v4
      with:
        name: junit-final-report
        path: junit-final-report.xml

    - name: Print test summary
      uses: mikepenz/action-junit-report@v5
      id: summary
      if: success() || failure()
      with:
        check_name: 'SIPssert tests report'
        report_paths: junit-final-report.xml
        annotate_only: true
        fail_on_failure: true
        detailed_summary: true
        group_suite: true
        include_passed: true

    - name: Add badge in summary
      if: always()
      run: |
        COLOR=${{ steps.summary.outputs.failed > 0 && 'red' || 'green' }}
        BADGE_URL="https://img.shields.io/badge/Tests-"
        BADGE_URL+="${{ steps.summary.outputs.passed }}%20passed,"
        BADGE_URL+="${{ steps.summary.outputs.failed }}%20failed,"
        BADGE_URL+="${{ steps.summary.outputs.skipped }}%20skipped"
        BADGE_URL+="-$COLOR"
        echo "![Tests]($BADGE_URL)" >> $GITHUB_STEP_SUMMARY
